### ISSUE TITLE
Player count

### ISSUE THREAD

**Issue by IkHadHonger** [DBmaoha/Super.Mixed.Game#19]
Hi what is the recommended playercount for gruntmode?

**Comment by DBmaoha** [comment]
whatever you like, depend on your own playstyle

**Comment by IkHadHonger** [comment]
I mean with gruntmode 2 from enderboy 12v12 has serious server lags thats why im
Asking

**Comment by DBmaoha** [comment]
you can try 8v8 or 6v6. idk how gruntmode2 code npc spawns, 6v6 is good for my version of gruntmode
