### ISSUE TITLE
disable gruntmode

### ISSUE THREAD

**Issue by IkHadHonger** [DBmaoha/Super.Mixed.Game#20]
hi is it possible to diable gruntmode so that its just like attrition but with all the Ai from gruntmode?

**Comment by DBmaoha** [comment]
I didn't left such setting, but it's possible. go `gruntmode.gnut` and comment out `BecomesGruntMode_Init()`

**Comment by DBmaoha** [comment]
If you also want to use titans and boosts, comment out `Riff_ForceBoostAvailability( eBoostAvailability.Disabled )` and `Riff_ForceTitanAvailability( eTitanAvailability.Never )`

**Comment by IkHadHonger** [comment]
thnx, will disable gruntmode also be a toggle in future update?

**Comment by IkHadHonger** [comment]
> I didn't left such setting, but it's possible. Go `gruntmode.gnut`, comment out `BecomesGruntMode_Init()` and `ClassicMP_SetCustomIntro( ClassicMP_GruntModeIntro_Setup, GRUNTMODE_INTRO_LENGTH )`. After that you will have gruntmode npc spawn, but players won't become grunts

thnx this is working.

Im looking for disabling all the phase shift and holo/decoy scripts.
Is there an easy way to achieve this?

My goals is to install the phaseshift rework and another holopilot mod  bc now im unable to install these mods with grunt mode installed.

**Comment by IkHadHonger** [comment]
> > > I didn't left such setting, but it's possible. Go `gruntmode.gnut`, comment out `BecomesGruntMode_Init()` and `ClassicMP_SetCustomIntro( ClassicMP_GruntModeIntro_Setup, GRUNTMODE_INTRO_LENGTH )`. After that you will have gruntmode npc spawn, but players won't become grunts
> > 
> > 
> > thnx this is working.
> > Im looking for disabling all the phase shift and holo/decoy scripts. Is there an easy way to achieve this?
> > My goals is to install the phaseshift rework and another holopilot mod bc now im unable to install these mods with grunt mode installed.
> 
> It's hard to do so, there're many scripts binding together. But I can separent a mod that only has the same NPC spawns as gruntmode, no other scripts included. I will do that when I got time

That would be great thx

**Comment by IkHadHonger** [comment]
> > > I didn't left such setting, but it's possible. Go `gruntmode.gnut`, comment out `BecomesGruntMode_Init()` and `ClassicMP_SetCustomIntro( ClassicMP_GruntModeIntro_Setup, GRUNTMODE_INTRO_LENGTH )`. After that you will have gruntmode npc spawn, but players won't become grunts
> > 
> > 
> > thnx this is working.
> > Im looking for disabling all the phase shift and holo/decoy scripts. Is there an easy way to achieve this?
> > My goals is to install the phaseshift rework and another holopilot mod bc now im unable to install these mods with grunt mode installed.
> 
> It's hard to do so, there're many scripts binding together. But I can separent a mod that only has the same NPC spawns as gruntmode, no other scripts included. I will do that when I got time

if you do so will it also be compatible with FD?

**Comment by DBmaoha** [comment]
> > > > I didn't left such setting, but it's possible. Go `gruntmode.gnut`, comment out `BecomesGruntMode_Init()` and `ClassicMP_SetCustomIntro( ClassicMP_GruntModeIntro_Setup, GRUNTMODE_INTRO_LENGTH )`. After that you will have gruntmode npc spawn, but players won't become grunts
> > > 
> > > 
> > > thnx this is working.
> > > Im looking for disabling all the phase shift and holo/decoy scripts. Is there an easy way to achieve this?
> > > My goals is to install the phaseshift rework and another holopilot mod bc now im unable to install these mods with grunt mode installed.
> > 
> > 
> > It's hard to do so, there're many scripts binding together. But I can separent a mod that only has the same NPC spawns as gruntmode, no other scripts included. I will do that when I got time
> 
> if you do so will it also be compatible with FD?

No. FD has various files to code npc spawn waves, you have to change them youself if you want so

**Comment by DBmaoha** [comment]
Separented gamemode done here https://northstar.thunderstore.io/package/VoyageDB_Modding_Home/Attrition_Extended/
This issue will be closed

**Comment by DBmaoha** [comment]
Fixed in v1.2.1. Thanks for your bug report!
