### ISSUE TITLE
Crash on entering northstar mp menu

### ISSUE THREAD

**Issue by Fr4Ckt3r** [DBmaoha/Super.Mixed.Game#23]
```
[SCRIPT SV] [errr] COMPILE ERROR Undefined variable "Rodeo_SetTitanRodeoSequenceEnabled"
[SCRIPT SV] [errr] /modai/extra_ai_spawner.gnut line [1191] column [36]
```
nothing else enabled

**Comment by DBmaoha** [comment]
Seems like mods confict. Are you enabling other mods that changed the file `scripts/vscripts/titan/rodeo_titan.gnut`?

**Comment by Fr4Ckt3r** [comment]
apparently caused by Legonzaur.HoloShift
VTOL bugged and didn't disable it when I clicked at disable.
