### ISSUE TITLE
Attrition Extended Chinese NPC names

### ISSUE THREAD

**Issue by IkHadHonger** [DBmaoha/Super.Mixed.Game#24]
i Noticed some NPCs with chinese names.

Didnt have a screenshot but if noticed again ill send you.

btw is this mod also compatible with other game modes like frontier War and Bounty Hunt?

**Comment by DBmaoha** [comment]
I see. I'm from china so my mods are default to be chinese. I translate the mod to english before I upload and may missed some of the localization stuffs, thanks for notifying me that
This mod is not compatible with any other gamemodes, or I'd say this mod IS a new gamemode, I just make it pure server-side so other clients don't have to install it

**Comment by IkHadHonger** [comment]
> I see. I'm from china so my mods are default to be chinese. I translate the mod to english before I upload and may missed some of the localization stuffs, thanks for notifying me that
> This mod isn't compatible with any other gamemodes, or I'd say this mod IS a new gamemode, I just make it pure server-side, overwriting the existing mode attrition, so other clients don't have to install it

Alr then thnx for the new gamemode anyways its really fun gamemode within attrition.

**Comment by DBmaoha** [comment]
Should be fixed at some point. This issue is inactive and I'm gonna close it
