### ISSUE TITLE
Attrition Extended: SERVER compile error

### ISSUE THREAD

**Issue by Fr4Ckt3r** [DBmaoha/Super.Mixed.Game#27]
No other mods are enabled.
```
[SCRIPT SV] [errr] COMPILE ERROR Undefined variable "Vortex_GetRefiredProjectileMods"
[SCRIPT SV] [errr] mp/_codecallbacks.gnut line [1114] column [42]
```

**Comment by DBmaoha** [comment]
Are you using contents from this repository? I don't recommand doing that. It's better to use thunderstore release packs

**Comment by Fr4Ckt3r** [comment]
> Are you using contents from this repository? I don't recommand doing that. It's better to use thunderstore release packs
Yeah, I thought that this one will be better, since version on thunderstore was updated like a week ago.

**Comment by DBmaoha** [comment]
> > Are you using contents from this repository? I don't recommand doing that. It's better to use thunderstore release packs
> > Yeah, I thought that this one will be better, since version on thunderstore was updated like a week ago.

sometimes contents in this repo are still in testing and may cause many sort of problem, if I didn't push update to thunderstore it means I haven't done enough updates for a new release. use thunder store release packs to prevent these compile errors
