### ISSUE TITLE
Suggestion: Make Titans use countermeasures when being rodeoed.

### ISSUE THREAD

**Issue by BTFighter** [DBmaoha/Super.Mixed.Game#31]
Just a suggestion, don't even know if it's possible currently.

**Comment by DBmaoha** [comment]
It's in progress. along with npc monarch upgrading and npc legion smart core, still need some time to figure out how to fix them

**Comment by BTFighter** [comment]
Gotcha, thanks for the confirmation. Looking forward to it!

**Comment by DBmaoha** [comment]
titan rodeo countermeasure done in [v1.5.0](https://thunderstore.io/package/download/VoyageDB_Modding_Home/Attrition_Extended/1.5.0/), still needs testing on stability
