### ISSUE TITLE
Crash Attririon Extended 1.5.2

### ISSUE THREAD

**Issue by IkHadHonger** [DBmaoha/Super.Mixed.Game#37]
New error Attrition Extended.

`[23:04:28] [SCRIPT SV] [info] SCRIPT ERROR: [SERVER] RandomInt: max value (0) must be greater than 0
[23:04:28] [SCRIPT SV] [info]  -> index = RandomInt( podNodes.len() )
[23:04:28] [SCRIPT SV] [info]
CALLSTACK
*FUNCTION [SpawnIntroBatch()] /modifiers/gamemode_aitdm_extend.gnut line [765]

[23:04:28] [SCRIPT SV] [info] LOCALS
[index] 0
[i] 0
[ships] 0
[pods] 0
[introSpawnClass] "npc_soldier"
[node] NULL
[first] true
[startIndex] 0
[shipNodes] ARRAY
[podNodes] ARRAY
[dropShipNodes] ARRAY
[dropPodNodes] ARRAY
[team] 3
[this] TABLE

DIAGPRINTS

abnormal program termination
0024:fixme:msvcrt:__clean_type_info_names_internal (0000000005168788) stub
nswrap: northstar exited with status 3
`

**Comment by DBmaoha** [comment]
server'smap when this error happens?

**Comment by IkHadHonger** [comment]
> server's map when this error happens?

Homestead

**Comment by DBmaoha** [comment]
got it, I will add an error handle for it

**Comment by IkHadHonger** [comment]
ty

**Comment by DBmaoha** [comment]
should be fixed in v1.6.4

**Comment by DBmaoha** [comment]
please let me know if this crash ever happens again

**Comment by IkHadHonger** [comment]
> please let me know if this crash ever happens again

Ok
