### ISSUE TITLE
NPC archon and Brute4

### ISSUE THREAD

**Issue by IkHadHonger** [DBmaoha/Super.Mixed.Game#39]
Hi, you added Archon and Brute4 spawns so need to install Titanframework, Archon and Brute4 mods also on the server or only clients?

**Comment by DBmaoha** [comment]
Yes, you need to install their mods in order to make them spawn

**Comment by IkHadHonger** [comment]
> Yes, you need to install their mods in order to make them spawn

So clientside and server side?

**Comment by DBmaoha** [comment]
> > Yes, you need to install their mods in order to make them spawn
> 
> So clientside and server side?

of course, these mods are quired by client
