### ISSUE TITLE
泰坦降落是速降的声音和振动

### ISSUE THREAD

**Issue by liveskai** [DBmaoha/Super.Mixed.Game#42]
圆顶护罩降落是速降的声音和振动

**Comment by liveskai** [comment]
nessie-tempfix

**Comment by DBmaoha** [comment]
地图是新兴城镇对吗？那张图由于是封顶地图，在官服里面就是这么降泰坦的，北极星缺少这个细节所以我修了

**Comment by liveskai** [comment]
> 地图是新兴城镇对吗？那张图由于是封顶地图，在官服里面就是这么降泰坦的，北极星缺少这个细节所以我修了

是新兴城镇

**Comment by DBmaoha** [comment]
这样的话就不算个问题，是地图特性
不影响实际体验，只是小细节修复而已
