### ISSUE TITLE
消耗战运行一会就卡死

### ISSUE THREAD

**Issue by liveskai** [DBmaoha/Super.Mixed.Game#43]
消耗战运行一会就卡死

**Comment by liveskai** [comment]
DRASTIC MEMORY OVERFLOW: Fell out of small block heap!

**Comment by DBmaoha** [comment]
没有遇到过这种情况，可以试试在启动项内加上 `+sv_max_props_multiplayer 500000` 和 `+sv_max_prop_data_dwords_multiplayer 800000`

**Comment by DBmaoha** [comment]
如果是指消耗战extended，可能还需要把mod换成 [extra-ai-spawner](https://github.com/DBmaoha/Super.Mixed.Game/tree/extra-ai-spawner) 这个分支内的，thunderstore发布版本只适用于ns而不能给nscn用

**Comment by liveskai** [comment]
> 没有遇到过这种情况，可以试试在启动项内加上 `+sv_max_props_multiplayer 500000` 和 `+sv_max_prop_data_dwords_multiplayer 800000`

一直有这个启动项，我用的是nessie-tempfix

**Comment by liveskai** [comment]
> 没有遇到过这种情况，可以试试在启动项内加上 `+sv_max_props_multiplayer 500000` 和 `+sv_max_prop_data_dwords_multiplayer 800000`

卡死，每次log都不一样，就是卡死不动了

**Comment by DBmaoha** [comment]
仅靠这些我也不能得知是什么情况，这种情况一般会出现在死循环 ( `while(true)` 或者 `for( ; ; )` ) 没有wait的时候
我个人是把AI数目调高后进行测试没出现问题，有时间的话能否麻烦你先关闭tempfix试一试？暂且这么排查一下

**Comment by liveskai** [comment]
> nessie-tempfix

我是原版游戏用的nessie-tempfix
调高ai不会卡死，1-2人玩也不会卡死，3个人玩就会卡死

**Comment by liveskai** [comment]
泰坦战正常

**Comment by DBmaoha** [comment]
按照说到的情况我去测试了一下，本地三人监听服务器加速运行，游戏时间经过五小时是没什么问题的
平常我的独立服务器可以稳定运行一周左右，白天一般会满人并且AI数目有增加
所以我没办法判断问题，可以把log上传来看一下吗

**Comment by liveskai** [comment]
> 按照说到的情况我去测试了一下，本地三人监听服务器加速运行，游戏时间经过五小时是没什么问题的 平常我的独立服务器可以稳定运行一周左右，白天一般会满人并且AI数目有增加 所以我没办法判断问题，可以把log上传来看一下吗
[nslog2023-09-21 18-49-59.txt](https://github.com/DBmaoha/Super.Mixed.Game/files/12683875/nslog2023-09-21.18-49-59.txt)

**Comment by DBmaoha** [comment]
每次的log都是 `DRASTIC MEMORY OVERFLOW: Fell out of small block heap!` 这一条结尾的吗？

**Comment by liveskai** [comment]
> 每次的log都是 `DRASTIC MEMORY OVERFLOW: Fell out of small block heap!` 这一条结尾的吗？

对，ai是双倍
const int SQUADS_PER_TEAM = 8

const int REAPERS_PER_TEAM = 4

**Comment by liveskai** [comment]
不用nessie-tempfix之前我这样是可以稳定运行一天的

**Comment by DBmaoha** [comment]
是AI数目的问题，TTF2对于超出64个AI会出现问题
双倍的话，仅小兵就达到了64个，算上玩家的AI泰坦是有可能出现这种问题
试试下调到
SQUADS_PER_TEAM = 6
REAPERS_PER_TEAM = 4
看看会不会好一些？

**Comment by DBmaoha** [comment]
> 不用nessie-tempfix之前我这样是可以稳定运行一天的

可能因为tempfix调整了npc的生成方式导致的，北极星原版其实对于步兵类的生成非常拖沓，如果生成了运兵船那么有20s会不生成任何小兵
而tempfix则是按照波次生成，每15s检查一次并尝试生成一个队伍内缺少的所有步兵，因此会出现大量AI同时在场的情况

**Comment by liveskai** [comment]
> 这个也因服务器配置而异，我个人没办法断定具体原因，先试试下调数目看看

ai调回默认了还是会崩

**Comment by DBmaoha** [comment]
> > 这个也因服务器配置而异，我个人没办法断定具体原因，先试试下调数目看看
> 
> ai调回默认了还是会崩

现在依然是不安装tempfix就没问题对吗？

**Comment by liveskai** [comment]
> > > 这个也因服务器配置而异，我个人没办法断定具体原因，先试试下调数目看看
> > 
> > 
> > ai调回默认了还是会崩
> 
> 现在依然是不安装tempfix就没问题对吗？

对

**Comment by DBmaoha** [comment]
我也不清楚到底是怎么发生的，自己没遇到过
如果实在不行的话只好关掉tempfix，又或者最后排查一下完全关掉AI生成会不会出问题
可以把log放到压缩包里上传，我来看看他们之间有没有什么共同点

**Comment by liveskai** [comment]
> 我也不清楚到底是怎么发生的，自己没遇到过 如果实在不行的话只好关掉tempfix，又或者最后排查一下完全关掉AI生成会不会出问题 可以把log放到压缩包里上传，我来看看他们之间有没有什么共同点

**Comment by liveskai** [comment]
> 我也不清楚到底是怎么发生的，自己没遇到过 如果实在不行的话只好关掉tempfix，又或者最后排查一下完全关掉AI生成会不会出问题 可以把log放到压缩包里上传，我来看看他们之间有没有什么共同点

[21.zip](https://github.com/DBmaoha/Super.Mixed.Game/files/12687884/21.zip)

**Comment by DBmaoha** [comment]
试试看更新到 [ThunderStore Release](https://northstar.thunderstore.io/package/VoyageDB_Modding_Home/Nessie_Temp_Fix/) 的 Version 1.3.7
或者用 [nessie-temp-fix](https://github.com/DBmaoha/Super.Mixed.Game/tree/nessie-tempfix) 内最新的文件

**Comment by DBmaoha** [comment]
如果没有更新又或者用的不是thunderstore版本的话，有你可能刚好遇到一个有bug未发布的版本并且使用了

**Comment by liveskai** [comment]
> > > 我也不清楚到底是怎么发生的，自己没遇到过 如果实在不行的话只好关掉tempfix，又或者最后排查一下完全关掉AI生成会不会出问题 可以把log放到压缩包里上传，我来看看他们之间有没有什么共同点
> > 
> > 
> > [21.zip](https://github.com/DBmaoha/Super.Mixed.Game/files/12687884/21.zip)
> 
> 似乎也并不全都是因为 `DRASTIC MEMORY OVERFLOW: Fell out of small block heap!` 出问题的，你是在哪里、什么时候下载的tempfix？

就昨天21号才用的，是雷霆商店下载的

**Comment by liveskai** [comment]
我找到问题了，是我改_score的原因

**Comment by liveskai** [comment]
打扰了，就是改_score出现的问题，现在能稳定运行了，没问题了

**Comment by DBmaoha** [comment]
能解决就好，这样的话我先关闭issue了
