### ISSUE TITLE
【tempfix】显示bug-受到自伤且被敌对泰坦攻击后弹射 会对弹射者本人显示泰坦助攻

### ISSUE THREAD

**Issue by liveskai** [DBmaoha/Super.Mixed.Game#45]
显示bug
100%触发

**Comment by DBmaoha** [comment]
如果是指敌对泰坦弹射后其他玩家会收到泰坦助攻，那么这个是官服表现但北极星缺少，所以我修复了
如果是其他情况，能否上传一小段视频来看一看？

**Comment by liveskai** [comment]
> 如果是指敌对泰坦弹射后其他玩家会收到泰坦助攻，那么这个是官服表现但北极星缺少，所以我修复了 如果是其他情况，能否上传一小段视频来看一看？ 编辑：或者再具体描述一下触发情况也可以，我这边仅靠本地测试不太明白具体是指什么

是自己弹射后出现了助攻，不是敌人弹射

**Comment by DBmaoha** [comment]
感谢反馈，经测试后发现问题是出在 “受到自伤且被敌对泰坦攻击后” 弹射，会显示泰坦助攻
已在[ThunderStore发布版](https://northstar.thunderstore.io/package/VoyageDB_Modding_Home/Nessie_Temp_Fix/) Version1.3.8修复

如果更新后问题解决请再次反馈，我会关闭issue

**Comment by liveskai** [comment]
已解决
