### ISSUE TITLE
what is playlistvar?

### ISSUE THREAD

**Issue by dsavsdfagsdfgasd** [DBmaoha/Super.Mixed.Game#53]
this isnt a issue but I cant for the life of me find what playlistvar is. Any help is greatly appreciated

**Comment by DBmaoha** [comment]
The variables you can put in `setplaylistvaroverrides` are playlistvar, you can use them to modify the game but it isn't necessary

**Comment by dsavsdfagsdfgasd** [comment]
alright thanks
