### ISSUE TITLE
Script error

### ISSUE THREAD

**Issue by BTFighter** [DBmaoha/Super.Mixed.Game#55]
![image](https://github.com/DBmaoha/Super.Mixed.Game/assets/45516471/075b5168-e8f4-4017-8cd6-8aa13fe4adbe)

AI TDM Extended

**Comment by DBmaoha** [comment]
Tried to fix it in v1.6.7. This is due to I packed wrong release package, please let me know if it's fixed

**Comment by BTFighter** [comment]
Sorry for the very late reply.

Anyways, fixed. Thanks!
